sonar.projectKey=tannguyen51_FTravel
sonar.organization=tannguyen51

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=FTravel
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Directories
sonar.tests=test
sonar.test.inclusions=test/**

# Exclude generated files and build artifacts
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, lib/generated/**
sonar.test.exclusions=**/*.g.dart, **/*.freezed.dart
