// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9amIB-QM6Ak4W09yxAh7xzEze8tHwYAA',
    appId: '1:412860345150:web:7b588e8014b2ace8059a6f',
    messagingSenderId: '412860345150',
    projectId: 'travel-app-my-2d48b',
    authDomain: 'travel-app-my-2d48b.firebaseapp.com',
    databaseURL: 'https://travel-app-my-2d48b-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-my-2d48b.firebasestorage.app',
    measurementId: 'G-LKLZSYBT39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANoW7-Cq-g0giswBF-nlU5pO6QoBr2_hA',
    appId: '1:412860345150:android:eda9d8338c6706ab059a6f',
    messagingSenderId: '412860345150',
    projectId: 'travel-app-my-2d48b',
    databaseURL: 'https://travel-app-my-2d48b-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-my-2d48b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANdK7w3wLkyKnRQOqbzgCgIzKcADW7UUM',
    appId: '1:412860345150:ios:e4e9b89371ad65d9059a6f',
    messagingSenderId: '412860345150',
    projectId: 'travel-app-my-2d48b',
    databaseURL: 'https://travel-app-my-2d48b-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-my-2d48b.firebasestorage.app',
    iosClientId: '412860345150-r5chvotj9gafpb7j45ldd0er9vmdg66u.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANdK7w3wLkyKnRQOqbzgCgIzKcADW7UUM',
    appId: '1:412860345150:ios:e4e9b89371ad65d9059a6f',
    messagingSenderId: '412860345150',
    projectId: 'travel-app-my-2d48b',
    databaseURL: 'https://travel-app-my-2d48b-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-my-2d48b.firebasestorage.app',
    iosClientId: '412860345150-r5chvotj9gafpb7j45ldd0er9vmdg66u.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9amIB-QM6Ak4W09yxAh7xzEze8tHwYAA',
    appId: '1:412860345150:web:fc04530938ecc0a2059a6f',
    messagingSenderId: '412860345150',
    projectId: 'travel-app-my-2d48b',
    authDomain: 'travel-app-my-2d48b.firebaseapp.com',
    databaseURL: 'https://travel-app-my-2d48b-default-rtdb.firebaseio.com',
    storageBucket: 'travel-app-my-2d48b.firebasestorage.app',
    measurementId: 'G-58YXZCNXKD',
  );
}
